const Menu = [
  {
    id: 1,
    title: 'Cupcake Recipes',
    category: 'breakfast',
    price: 15.99,
    img: '../images/menu_1.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
    
  },
  {
    id: 2,
    title: 'Cupcake Recipe',
    category: 'lunch',
    price: 13.99,
    img: '../images/menu_1.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
  },
  {
    id: 3,
    title: 'Cupcake Recipe',
    category: 'shakes',
    price: 6.99,
    img: '../images/menu_1.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
  },
  {
    id: 4,
    title: 'Cupcake Recipe',
    category: 'breakfast',
    price: 20.99,
    img: '../images/menu_6.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
  },
  {
    id: 5,
    title: 'Cupcake Recipe',
    category: 'lunch',
    price: 22.99,
    img: '../images/menu_1.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
  },
  {
    id: 6,
    title: 'Cupcake Recipe',
    category: 'Dinner',
    price: 18.99,
    img: '../images/menu_1.jpg',
    item1: 'Juice Fruit',
    item2: 'Checken',
    item3: 'cherry',
    item4: 'milk',
    item5: 'tomato',
    item6: 'potato',
    item7: 'vegetable',
    item8: 'sesame',
    item9: 'chilly',
  },


];
export default Menu;